# Generated by Django 4.1.1 on 2022-09-24 09:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockValueImportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('ticker', models.CharField(max_length=5)),
                ('date', models.DateField(blank=True)),
                ('value_open', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('value_high', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('value_low', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('value_close', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('value_adjclose', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
