# Generated by Django 4.1.1 on 2022-09-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(choices=[('GOOG', 'Alphabet Inc.'), ('PLTR', 'Palantir Technologies Inc.'), ('TWTR', 'Twitter, Inc.'), ('SAP', 'SAP SE')], max_length=5)),
                ('date', models.DateField()),
                ('value_open', models.PositiveIntegerField()),
                ('value_high', models.PositiveIntegerField()),
                ('value_low', models.PositiveIntegerField()),
                ('value_close', models.PositiveIntegerField()),
                ('value_adjclose', models.PositiveIntegerField()),
                ('volume', models.PositiveIntegerField()),
            ],
        ),
    ]
