# Generated by Django 4.1.1 on 2022-09-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockvalue',
            name='value_adjclose',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_close',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_high',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_low',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_open',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='volume',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
    ]
