# Generated by Django 4.1.1 on 2022-09-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stockvalue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockvalue',
            name='value_adjclose',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_close',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_high',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_low',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='value_open',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
