# Generated by Django 4.1.1 on 2022-09-26 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stockvalue_created_stockvalue_is_removed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='stockvalue',
            name='ticker',
            field=models.CharField(choices=[('GOOG', 'Alphabet Inc.'), ('PLTR', 'Palantir Technologies Inc.'), ('TWTR', 'Twitter, Inc.'), ('SAP', 'SAP SE')], db_index=True, max_length=5),
        ),
        migrations.AddField(
            model_name='stockvalue',
            name='symbol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stocks.stocksymbol'),
            preserve_default=False,
        ),
    ]
